title: bwright94's GitHub Page
description: Welcome to my GitHub Page.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
